version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: satuwarga-api
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=satuwarga
      - DB_PASSWORD=onewarga!
      - DB_NAME=satuwarga
    volumes:
      - ./keys:/app/keys

  db:
    image: postgres:latest
    container_name: satuwarga-database
    restart: always
    environment:
      POSTGRES_USER: satuwarga
      POSTGRES_PASSWORD: onewarga!
      POSTGRES_DB: satuwarga
    volumes:
      - satuwarga_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    image: nginx:alpine
    container_name: satuwarga-nginx
    ports:
      - "3000:80"  # akses dari IP publik: http://your-ip:8080
    volumes:
      - /home/satuwarga/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/satuwarga/frontend:/usr/share/nginx/html
    depends_on:
      - go-app

volumes:
  satuwarga_pgdata: